- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed

        - type: twitch-channels
          channels:
            - pyrionflax
            - zisteau
            - dota2ti
            - quincy1874

    - size: full
      widgets:
        - type: group
          widgets:
            - type: reddit
              subreddit: HordeApp
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

        - type: bookmarks
          groups:
            - links:
                - title: Kibana
                  url: https://fac7764259cf4ab18480e55bbea89f81.westeurope.azure.elastic-cloud.com:9243/app/kibana#/home
                - title: Formalize
                  url: https://app.formalize.com/
            - title: Azure
              color: 200 50 50
              links:
                - title: PIM
                  url: https://portal.azure.com/#view/Microsoft_Azure_PIMCommon/ActivationMenuBlade/~/azurerbac
                - title: Entra ID
                  url: https://entra.microsoft.com/#home
                - title: 365 Admin
                  url: https://admin.microsoft.com/Adminportal/Home?#/homepage
                - title: DevOps
                  url: https://dev.azure.com/HordeOrg/

    - size: small
      widgets:
        - type: weather
          location: Bergen, Norway
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "12h"
          # Optionally hide the location from being displayed in the widget
          hide-location: true

        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: horde.no
              url: https://horde.no/
              check-url: https://horde.no/.well-known/pgpkey.txt
              icon: auto-invert https://horde.no/icons/icon-72x72.png

        - type: server-stats
          servers:
            - type: local
              name: Local metrics
